name: yg-warp-plus
on:
  workflow_dispatch:
  watch:
    types: started
  #push:
  #  branches: [ main ]
  repository_dispatch:
    types: 同步仓库
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync My-Actions
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ygkkkyb/warp-plus.git"
          source_branch: "master"
          destination_branch: "yg-warp-plus"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}
